# Train Test Frameworks walkthrough

In [8]:
X = list(range(10))
print(X)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
y = [x*x for x in X]
print(y)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


## Split Data

In [14]:
import sklearn.model_selection as model_selection

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.75,test_size=0.25, random_state=101)

print ("X_train: ", X_train)
print ("y_train: ", y_train)
print("X_test: ", X_test)
print ("y_test: ", y_test)


X_train:  [4 9 3 5 7 6 1]
y_train:  [16 81  9 25 49 36  1]
X_test:  [8 2 0]
y_test:  [64  4  0]


## Cross Validation

In [15]:
from sklearn.model_selection import KFold
import numpy as np

kf = KFold(n_splits=5)
X = np.array(X)
y = np.array(y)
for train_index, test_index in kf.split(X):
    print(train_index, test_index)
    # X_train, X_test = X[train_index], X[test_index]
    # y_train, y_test = y[train_index], y[test_index]
    print("X_test: ", X_test)

[2 3 4 5 6 7 8 9] [0 1]
X_test:  [8 2 0]
[0 1 4 5 6 7 8 9] [2 3]
X_test:  [8 2 0]
[0 1 2 3 6 7 8 9] [4 5]
X_test:  [8 2 0]
[0 1 2 3 4 5 8 9] [6 7]
X_test:  [8 2 0]
[0 1 2 3 4 5 6 7] [8 9]
X_test:  [8 2 0]
