## eigendecomposition exercise

In [2]:
import numpy
import numpy as np
import math

**Task:** Create a matrix (2x2) called matrix 'A'.


In [3]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [6]:
def shape_2x2(matrix):
    """
    Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

    PARAMS:
        matrix (numpy.ndarray) - matrix to check
    RETURN:
        True (bool) - if matrix has shape 2x2
        False (bool) - if matrix has not shape 2x2

    """

    if matrix.shape == (2,2):
        return True
    else:
        return False

In [7]:
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [8]:
def determinant_2x2(matrix):
    """
    Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

    PARAMS:
        matrix (numpy.ndarray) - matrix to compute determinant
    RETURN:
        det (float) - matrix determinant

    """

    determinant = (matrix[0][0]*matrix[1][1]) - (matrix[0][1]*matrix[1][0])

    return determinant

In [9]:
determinant_2x2(A)

-2

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [10]:
determinant_2x2(A)

-2

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [11]:
eiganvals, V = np.linalg.eig(A)

**Task:** Print the eigenvalues.

In [12]:
print(eiganvals)

[-0.37228132  5.37228132]


**Task:** Print  the eigenvectors.

In [13]:
print(V)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [ ]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

In [14]:
def eig_2x2(matrix):
    """
    Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

    PARAMS:
        matrix (numpy.ndarray) - matrix to perform decomposition
    RETURN:
        eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

    """

    eigenvalues = []
    eigenvectors = [[],[]]

    if shape_2x2(matrix):
        determinant = determinant_2x2(matrix)
        trace = matrix[0][0] + matrix[1][1]
        try:
            discriminant = math.sqrt(trace ** 2 -(4*determinant))
        except ValueError:
            print('ValueError')
            return None

        eigenvalues.append((trace - discriminant)/2)
        eigenvalues.append((trace + discriminant)/2)

        for eigen in eigenvalues:
            ratio = (eigen-matrix[0][0])/matrix[0][1]
            # choose any value for x to get an eigenvector that is not normalized:
            x = -1
            y = ratio * x
            #normalize eigenvector:
            norm_x = x/(math.sqrt(x**2 + y**2))
            norm_y = y/(math.sqrt(x**2 + y**2))
            eigenvectors[0].append([norm_x])
            eigenvectors[1].append([norm_y])

        return (eigenvalues,eigenvectors)
    else:
        return None

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [15]:
eig_2x2(A)

([-0.3722813232690143, 5.372281323269014],
 [[[-0.8245648401323938], [-0.41597355791928425]],
  [[0.5657674649689923], [-0.9093767091321241]]])

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [16]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [17]:
B = np.array([[0,1],[-1,0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [18]:
eig_2x2(B)

ValueError


**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [19]:
eigenvalue , eigenvector = np.linalg.eig(B)

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [20]:
print(eigenvalue)
print(eigenvector)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]
