# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [4]:
def null_array(n):
    x=np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
def null_array(n):
    x=np.zeros(n)
    x[4] = 1
    return x
print(null_array(10))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
np.flip(v)

# or i can use v=v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [16]:
indices = (1,2,0,0,4,0)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [17]:
a = np.random.random((3,3,3))
print(a)

[[[0.60329055 0.28636279 0.65597534]
  [0.09727412 0.16751308 0.77697983]
  [0.92390396 0.88952445 0.19402739]]

 [[0.24225286 0.28734884 0.31534971]
  [0.42317749 0.19924951 0.10084312]
  [0.33608244 0.19803458 0.3453088 ]]

 [[0.85948185 0.1367764  0.09711439]
  [0.96388761 0.0934012  0.13453751]
  [0.6655905  0.79738795 0.04642845]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
arr = np.random.randint(100,size=(10,10))
print(np.min(arr))
print(np.max(arr))

0
99


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
b = np.random.random(10)
c = b.mean()
print(c)

0.5120261637056702


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [53]:
d = np.ones((10,10))
d[1:-1,1:-1] = 0

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [54]:
Z = np.ones((5,5))

Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [24]:
e = np.diag(1+np.arange(4), k = -1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [26]:
z = np.random.random((5,5))
zmax, zmin, = z.max(), z.min()
z = (z-zmin)/ (zmax-zmin)
print(z)

[[0.95404944 0.48902235 0.83362109 0.35716955 0.77533534]
 [0.13693002 0.41891208 0.89998113 0.36847672 0.43379238]
 [0.20452201 0.25746365 0.16720242 0.6483511  0.32275388]
 [0.         0.54788677 1.         0.24506977 0.28501831]
 [0.16388751 0.36624432 0.65812923 0.75500181 0.4136487 ]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [45]:
# Author: Evgeni Burovski

Z = np.arange(11)

Z[(3 < Z) & (Z <= 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 18. How to round away from zero a float array ? (★☆☆)

In [46]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)

print (np.copysign(np.ceil(np.abs(Z)), Z))

[  5.   5.   5.  -7. -10.  -6.  -5.  -4.   8.  -4.]


#### 19. Find common values between two arrays? (★☆☆)

In [47]:
Z1 = np.random.randint(0,10,10)

Z2 = np.random.randint(0,10,10)

print(np.intersect1d(Z1,Z2))

[0 3 4 8]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
np.sqrt(-1) == np.emath.sqrt(-1)


<ipython-input-48-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [51]:
def generate():

    for x in range(10):

        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [27]:
z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [28]:
z = np.random.random(10)
z.sort()
print(z)

[0.13463262 0.30173073 0.31959369 0.43438914 0.56923171 0.61110258
 0.63413495 0.85161823 0.86899422 0.91827553]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [29]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [30]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)


[0.39049502 0.73569846 0.38607817 0.88648566 0.3389088  0.73437496
 0.92277665 0.80537649 0.16773003 0.        ]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [44]:
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.random.random(10)
print(array)
# [ 0.21069679  0.61290182  0.63425412  0.84635244  0.91599191  0.00213826
#   0.17104965  0.56874386  0.57319379  0.28719469]

value = 0.5

print(find_nearest(array, value))

[0.25443426 0.20289823 0.78910326 0.41276699 0.21226592 0.42332917
 0.93727159 0.45882561 0.8627159  0.41888849]
0.45882560825178986


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [36]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. Sort an array by the nth column? (★★☆)

In [ ]:
z = np.random.randint(0,10,(3,3))
print(z)
print

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [34]:
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [31]:
z = np.array([1,2,3,4,5])
nz = 3
z0 =np.zeros(len(z)+(len(z)-1)*(nz))
z0[::nz+1] = z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [32]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [43]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[1 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1
 1 1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 1
 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 1]
Negating a boolean: 
[0 0 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0
 0 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 1 0
 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0]
original: 
[ 0.04687032  0.79759347  0.83145978 -0.36270128  0.79396998 -0.76040639
 -0.21672511 -0.86269756 -0.91014331  0.45319223]
Change the sign of float inplace: 
[-0.04687032 -0.79759347 -0.83145978  0.36270128 -0.79396998  0.76040639
  0.21672511  0.86269756  0.91014331 -0.45319223]


#### 33. Find the most frequent value in an array?

In [37]:
z = np.random.randint(0,10,50)
print(z)
print('rank:', np.bincount(z).argmax())


[7 7 9 6 0 2 9 3 7 6 1 2 6 7 9 7 4 1 2 3 4 9 1 1 1 4 5 6 8 0 5 2 5 0 2 2 2
 7 3 9 6 5 4 9 4 0 2 8 7 3]
rank: 2


#### 34. Get the n largest values of an array (★★★)

In [38]:
z = np.arange(1000)
np.random.shuffle(z)
n = 5

print(z[np.argsort(z)[:n]])
print(z[np.argpartition(-z,n)[:n]])


[0 1 2 3 4]
[996 997 999 995 998]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [42]:
z = np.random.randint(0,2,(6,3))
t = np.ascontiguousarray(z).view(np.dtype((np.void, z.dtype.itemsize * z.shape[1])))
_, idx = np.unique(t, return_index=True)
uz = z[idx]
print(uz)

# Author: Jaime Fernández del Río

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 0]]
